import { Circulo, Quadrado } from "./style";

function Pontilhado() {
  return (
      <>
            <Quadrado>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
                <Circulo/>
        
              
                
                

            </Quadrado>
            
        
      </>
        
    
  );
}

export default Pontilhado